### ISSUE TITLE
[bug]use other name,cert-production.pem and key-production.pem can not do.

### ISSUE THREAD

**Issue by chelsh** [argon/node-apn#253] opened 2015-03-23 04:21 UTC
if(pushEnv=='Production'){
    isProduction=true;
    certDirctory='cert-production.pem';
    keyDirectory='key-production.pem';
}

var service = new apn.connection({ production: isProduction,cert:certDirctory,key:keyDirectory});

---- it will error:
Mon, 23 Mar 2015 04:20:23 GMT uncaughtException certificate does not support configured environment, production: true
Server-API-0 (err): Error: certificate does not support configured environment, production: true
Server-API-0 (err):     at validateCredentials (/data/Server-API/source/node_modules/apn/lib/credentials/validate.js:19:10)
Server-API-0 (err):     at /data/Server-API/source/node_modules/apn/lib/feedback.js:142:5
Server-API-0 (err):     at _fulfilled (/data/Server-API/source/node_modules/apn/node_modules/q/q.js:794:54)
Server-API-0 (err):     at self.promiseDispatch.done (/data/Server-API/source/node_modules/apn/node_modules/q/q.js:823:30)
Server-API-0 (err):     at Promise.promise.promiseDispatch (/data/Server-API/source/node_modules/apn/node_modules/q/q.js:756:13)
Server-API-0 (err):     at /data/Server-API/source/node_modules/apn/node_modules/q/q.js:564:44
Server-API-0 (err):     at flush (/data/Server-API/source/node_modules/apn/node_modules/q/q.js:110:17)

**Comment by argon** [comment] 2015-03-24 09:43
I used your example to try to reproduce the problem and it works perfectly. The code I used can be seen here: https://gist.github.com/argon/bdce088a1043ef655e0b

As the error says, you have configured the module with a certificate which is incorrect for connecting to the production environment. Double check your certificates are the right way round.

```
$ node apn
{ cert: 'cert-production.pem',
  key: 'key-production.pem',
  ca: null,
  pfx: null,
  passphrase: null,
  production: true,
  voip: false,
  address: 'gateway.push.apple.com',
  port: 2195,
  rejectUnauthorized: true,
  cacheLength: 1000,
  autoAdjustCache: true,
  maxConnections: 1,
  connectTimeout: 10000,
  connectionTimeout: 3600000,
  connectionRetryLimit: 10,
  buffersNotifications: true,
  fastMode: false,
  disableNagle: false,
  disableEPIPEFix: false }
Connected
Transmitted:  { encoding: 'utf8',
  payload: { aps: { alert: 'Hello' } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  alert: 'Hello',
  badge: undefined,
  sound: undefined,
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: '{"aps":{"alert":"Hello"}}',
  truncateAtWordEnd: false,
  urlArgs: undefined,
  category: undefined }
Completed!
Transmission Error 8
$
```

**Comment by chelsh** [comment] 2015-03-25 09:37
![1d86efb4-b458-4bac-888e-dee935cb56ee_meitu_1](https://cloud.githubusercontent.com/assets/10752360/6821687/38e3c118-d314-11e4-974a-bec0020c57c4.png)

**Comment by chelsh** [comment] 2015-03-25 09:37
is this ok?:)

**Comment by argon** [comment] 2015-03-25 09:39
Does the code example I sent work for you?

**Comment by chelsh** [comment] 2015-03-25 10:06
https://gist.github.com/argon/bdce088a1043ef655e0b  this link?  i can not open it:(
can you paste the code example here？：）

**Comment by chelsh** [comment] 2015-03-25 10:07
i can open it now：）

**Comment by chelsh** [comment] 2015-03-25 10:11
whwdeMacBook-Pro:Pro whw$ node apn.js
{ cert: 'cert-production.pem',
  key: 'key-production.pem',
  ca: null,
  pfx: null,
  passphrase: null,
  production: true,
  voip: false,
  address: 'gateway.push.apple.com',
  port: 2195,
  rejectUnauthorized: true,
  cacheLength: 1000,
  autoAdjustCache: true,
  maxConnections: 1,
  connectTimeout: 10000,
  connectionTimeout: 3600000,
  connectionRetryLimit: 10,
  buffersNotifications: true,
  fastMode: false,
  disableNagle: false,
  disableEPIPEFix: false }
Connected
Transmitted:  { encoding: 'utf8',
  payload: { aps: { alert: 'Hello' } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  alert: 'Hello',
  badge: undefined,
  sound: undefined,
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: '{"aps":{"alert":"Hello"}}',
  truncateAtWordEnd: false,
  urlArgs: undefined,
  category: undefined }
Completed!
Transmission Error 8

**Comment by chelsh** [comment] 2015-03-25 10:13
whwdeMacBook-Pro:Pro whw$ ls -lrt
total 80
-rw-r--r--@ 1 whw  staff   960  3 21 15:30 rehuproduction.certSigningRequest
-rw-r--r--@ 1 whw  staff   952  3 21 15:30 rehuaps.certSigningRequest
-rw-r--r--@ 1 whw  staff  7987  3 21 15:30 rehuDistribution.mobileprovision
-rw-r--r--@ 1 whw  staff  3155  3 21 15:30 key-production.p12
-rw-r--r--@ 1 whw  staff  1407  3 21 15:30 cert-production.cer
-rw-r--r--  1 whw  staff  1960  3 22 18:15 cert-production.pem
-rw-r--r--  1 whw  staff  4173  3 22 18:15 key-production.pem
-rw-r--r--@ 1 whw  staff  1267  3 24 17:42 apn.js
drwxr-xr-x  3 whw  staff   102  3 25 18:10 node_modules

**Comment by chelsh** [comment] 2015-03-25 10:16
it is ok?

**Comment by argon** [comment] 2015-03-25 10:21
Yes, that indicates there isn't a problem with the module on your machine. Perhaps you have a configuration issue. 

Unfortunately the piece you included in the first post is not sufficient to diagnose further. If you want to email me privately with the code you're using to setup the apn connection I'm happy to help. 

\A

**Comment by chelsh** [comment] 2015-03-25 10:25
var pushEnv=='IOS_ENV_PRO'
var isProduction=false;
var certDirctory='cert.pem';
var keyDirectory='key.pem';
if(pushEnv=='IOS_ENV_PRO'){
    isProduction=true;
    certDirctory='cert-production.pem';
    keyDirectory='key-production.pem';
}
console.log(certDirctory);
console.log(keyDirectory);
var service = new apn.connection({ production: isProduction,cert:certDirctory,key:keyDirectory});

------log:
cert-production.pem
key-production.pem
Wed, 25 Mar 2015 10:23:09 GMT uncaughtException ENOENT, open 'cert.pem'
Error: ENOENT, open 'cert.pem'
    at Error (native)

**Comment by chelsh** [comment] 2015-03-25 10:27
it must have the cert.pem and key.pem in the directory? if i only need use the cert-production.pem and key-production.pem.

**Comment by chelsh** [comment] 2015-03-25 10:33
my code:

![image](https://cloud.githubusercontent.com/assets/10752360/6822774/44efa036-d31d-11e4-89d9-8b0261c38504.png)


![image](https://cloud.githubusercontent.com/assets/10752360/6822794/5c002976-d31d-11e4-853c-36e559c4ff37.png)

**Comment by chelsh** [comment] 2015-03-25 10:36
my code:
![image](https://cloud.githubusercontent.com/assets/10752360/6822855/c1f5a134-d31d-11e4-9b72-149bdc577ada.png)

**Comment by chelsh** [comment] 2015-03-25 10:37
my log:
![image](https://cloud.githubusercontent.com/assets/10752360/6822877/f1bcdea0-d31d-11e4-91d1-1eb277b9b2c8.png)

**Comment by chelsh** [comment] 2015-03-25 10:45
when i move cert.pem,key.pem,cert-production.pem,key-production.pem to another position,then error:
![image](https://cloud.githubusercontent.com/assets/10752360/6823005/0e506ef0-d31f-11e4-8d41-9b2ce0968e86.png)

**Comment by argon** [comment] 2015-03-25 13:51
The file location in the latest screenshot is correct. The path for `cert` and `key` is relative to the directory the application is started from. In this case `Server-API2`, not `Server-API2/lib/XingPush/lib`.

The error you are seeing means that the `cert-production.pem` file **does not contain** a production certificate.
> certificate does not support configured environment, production: true

If you **email** me a copy of `cert-production.pem`, I can take a look at it and see what is wrong with the certificate. The certificate file is *useless* without the key file so I can not do anything with it. I just need to see what data is contains.

**Comment by chelsh** [comment] 2015-03-26 02:17
OK,how can i give you the cert-production.pem,what is your email?

**Comment by chelsh** [comment] 2015-03-26 02:18
argon@mkbot.net ?:)

**Comment by chelsh** [comment] 2015-03-26 03:07
![image](https://cloud.githubusercontent.com/assets/10752360/6839746/358d6dfe-d3a8-11e4-82bd-959abb7cef40.png)

**Comment by chelsh** [comment] 2015-03-26 03:07
have sent to you

**Comment by argon** [comment] 2015-03-26 09:30
I have tested your `cert-production.pem` file. Using the simplest possible test-case it is recognised as a valid certificate.

I am confused because the check you performed in https://github.com/argon/node-apn/issues/253#issuecomment-85969824 also shows the certificate is valid but you're still seeing the problem in your application. Did you definitely send me the exact file from the application directory?

**Comment by chelsh** [comment] 2015-03-26 14:09
yes,i send the correct file:),
key.pem and cert.pem are for development,i set production:false ,and they are all ok.
key-production.pem and cert-production.pem are for production,i set production:true,but they are not ok:(

**Comment by argon** [comment] 2015-03-26 14:12
But in https://github.com/argon/node-apn/issues/253#issuecomment-85969824 you said the example code works and it does _exactly the same thing_. Something doesn't add up. I will need to add some debugging to the module to be able to help you further. I'll let you know when I've got something for you to try.

**Comment by chelsh** [comment] 2015-03-26 14:23
yes,thank you very much,wait for your message:)

**Comment by chelsh** [comment] 2015-03-26 14:42
logs:
pushEnv:IOS_ENV_PRO
cert-production.pem
key-production.pem
{ cert: 'cert-production.pem',
  key: 'key-production.pem',
  ca: null,
  pfx: null,
  passphrase: null,
  production: true,
  voip: false,
  address: 'gateway.push.apple.com',
  port: 2195,
  rejectUnauthorized: true,
  cacheLength: 1000,
  autoAdjustCache: true,
  maxConnections: 1,
  connectTimeout: 10000,
  connectionTimeout: 3600000,
  connectionRetryLimit: 10,
  buffersNotifications: true,
  fastMode: false,
  disableNagle: false,
  disableEPIPEFix: false }
::ffff:127.0.0.1 - - [26/Mar/2015:14:38:04 +0000] "POST /1.1/topic/add HTTP/1.1" 200 484 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36"
APNS Connected
APNS Notification transmitted to:13fd954f49b023da1853308b6605647a6b27447f91c7f12c55799baea0eff592
APNS Notification caused error: 8 for device  { token: <Buffer 13 fd 95 4f 49 b0 23 da 18 53 30 8b 66 05 64 7a 6b 27 44 7f 91 c7 f1 2c 55 79 9b ae a0 ef f5 92> } { encoding: 'utf8',
APNS A error code of 8 indicates that the device token is invalid. This could be for a number of reasons - are you using the correct environment? i.e. Production vs. Sandbox
  payload: 
APNS Disconnected
   { topicId: '551419cb7a786ed8013ff773',
     topicReplyId: '',
     aps: 
      { badge: 15,
        sound: 'duang.caf',
        alert: 'hhhhhhhhhh1',
        category: 'INVITE_CATEGORY' } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  alert: 'hhhhhhhhhh1,
  badge: 15,
  sound: 'haha.caf',
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: '{"topicId":"551419cb7a786ed8013ff773","topicReplyId":"","aps":{"badge":15,"sound":"haha.caf","alert":" hhhhhhhhhh1","category":"INVITE_CATEGORY"}}',
  truncateAtWordEnd: false,
  urlArgs: undefined,
  category: 'INVITE_CATEGORY' }

----it is ok now,but transmitted not success.my app is loaded from xcode.

**Comment by argon** [comment] 2015-03-28 10:48
If the app is loaded from Xcode then you should not use the production environment. Only apps downloaded from the App store will be connected to the production environment.

As you have fixed your certificate problems I will be closing this issue.

**Closed by argon** 2015-03-28 10:48 UTC

**Comment by laloneferrero** [comment] 2015-11-27 00:51
Hi argon thanks for your awesome code, How can I test the production certificates without uploading the app to the Appstore?, I make the ipa file with the organizer and install into my phone via diawi, its a valid way to test the production certificates?

**Comment by argon** [comment] 2015-11-27 07:43
If you build your app with an AdHoc provisioning profile it will use the production APN gateway

**Comment by laloneferrero** [comment] 2015-11-27 21:16
Thanks argon :)
