### ISSUE TITLE
TypeError: Cannot call method 'resolve' of null

### ISSUE THREAD

**Issue by deepakc** [argon/node-apn#285] opened 2015-07-13 14:54 UTC
I am seeing this error occasionally,
where it couldn't resolve the promise in case of a socket error and throws a TypeError.
From my logs, i could see the connection is re-established and the notifications are getting pushed, but the notification doesn't gets transmitted to few devices when i see this error. Maybe few device ids is lost in a broken pipe?
Any idea why this occurs ?

2015-07-13T07:14:42.861Z - TypeError: Cannot call method 'end' of undefined
2015-07-13T07:14:42.888Z - Socket Error occurred
2015-07-13T07:14:42.907Z - Socket Error : Error: Connect timed out
...
...
2015-07-13T07:14:46.500Z - TypeError: Cannot call method 'resolve' of null

**Comment by argon** [comment] 2015-08-11 14:51
Are you definitely running the latest version of `node-apn`? The top error you quote currently has a guard around it so the method `end` should not be called if it is undefined.

**Comment by deepakc** [comment] 2015-08-11 14:55
I am using 1.7.3. Upgrading it to 1.7.4 should get rid of it?

**Comment by argon** [comment] 2015-08-11 16:12
It should do, yes.

**Comment by argon** [comment] 2015-09-19 00:37
I'm going to close this as I assume the problem is now resolved. Feel free to reopen if you are still seeing it.

**Closed by argon** 2015-09-19 00:37 UTC
