### ISSUE TITLE
 APNS Notification caused error: 8 for device

### ISSUE THREAD

**Issue by chelsh** [argon/node-apn#257] opened 2015-03-26 10:58 UTC
```
Server-API-0 (out): APNS Notification transmitted to:e017cc98d7780f1ef4dae66c36a663026253d9a71aedf4149eabe87ff5cc057d
Server-API-0 (out): APNS Notification transmitted to:37dad0ababa04908d85454e20c61703c838c34d004234412dd60d9d4dae67ab9
Server-API-0 (err): APNS Notification caused error: 8 for device  { token: <Buffer e0 17 cc 98 d7 78 0f 1e f4 da e6 6c 36 a6 63 02 62 53 d9 a7 1a ed f4 14 9e ab e8 7f f5 cc 05 7d> } { encoding: 'utf8',
Server-API-0 (err):   payload: 
Server-API-0 (err):    { topicId: '5513e50694330fb8453f9c55',
Server-API-0 (err):      topicReplyId: '',
Server-API-0 (err):      aps: 
Server-API-0 (err):       { badge: 8,
Server-API-0 (err):         sound: 'haha.caf',
Server-API-0 (err):         alert: 'hahhahahha',
Server-API-0 (err):         category: 'INVITE_CATEGORY' } },
Server-API-0 (err):   expiry: 0,
Server-API-0 (err):   priority: 10,
Server-API-0 (err):   retryLimit: -1,
Server-API-0 (err):   device: undefined,
Server-API-0 (err):   alert: 'hahhahahha',
Server-API-0 (err):   badge: 8,
Server-API-0 (err):   sound: 'haha.caf',
Server-API-0 (err):   newsstandAvailable: undefined,
Server-API-0 (err):   contentAvailable: undefined,
Server-API-0 (err):   mdm: undefined,
Server-API-0 (err):   compiled: '{"topicId":"5513e33334330fb8453f9c55","topicReplyId":"","aps":{"badge":8,"sound":"haha.caf","alert":"hahhahahha","category":"INVITE_CATEGORY"}}',
Server-API-0 (err):   truncateAtWordEnd: false,
Server-API-0 (err):   urlArgs: undefined,
Server-API-0 (err):   category: 'INVITE_CATEGORY' }
Server-API-0 (out): APNS A error code of 8 indicates that the device token is invalid. This could be for a number of reasons - are you using the correct environment? i.e. Production vs. Sandbox
Server-API-0 (out): APNS Disconnected
```

**Comment by argon** [comment] 2015-03-26 13:50
Are you trying to run the code in a production environment? If so that will only work when the app has been downloaded from the App Store. If you have loaded the app onto the device through Xcode it will return a token for the development sandbox.

**Comment by chelsh** [comment] 2015-03-26 14:15
yes,i loaded the app onto the device through Xcode,and my pem is key.pem and cert.pem, the two pem are for development,and the production of apn is false

**Comment by argon** [comment] 2015-03-26 14:16
The device token is wrong then. Make sure you regenerate it from the app.

This is not a problem with node-apn, but rather you have the wrong token for the device. This is an error from Apple that the device identifier is not recognised.

**Comment by chelsh** [comment] 2015-03-26 14:19
but another device tokens are ok, they are all generated by the same program:(

**Comment by chelsh** [comment] 2015-03-26 14:20
let me have double check:)

**Comment by argon** [comment] 2015-03-31 08:46
Did you make any progress with resolving this?

**Comment by mattfiocca** [comment] 2015-04-07 21:54
I think I might be experiencing the same issue here. when i try our dev certs, set production:false, I get no errors and a completed transmission, though no notification on my device shows up. When i try our production certs, set production:true, i also get this transmissionError 8, invalid token, despite the token being generated from the device in question. I am running nodejs locally for these tests however, not sure of that matters?

Production Settings:
```
$ DEBUG=apn node push_notification.js 
  apn Initialising connection +0ms
  apn Initialising module +2ms
  apn 1 left to send +2ms
  apn Connection established +373ms
connected 1
  apn Socket drained +107ms 0
transmitted { encoding: 'utf8',
  payload: 
   { description: 'This is a test',
     aps: { badge: 1, sound: 'dong.aiff', alert: 'Testing' } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  alert: 'Testing',
  badge: 1,
  sound: 'dong.aiff',
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: '{"description":"This is a test","aps":{"badge":1,"sound":"dong.aiff","alert":"Testing"}}',
  truncateAtWordEnd: false,
  urlArgs: undefined,
  category: undefined } { token: <Buffer c6 ce ac 1e f7 f5 ed c8 13 66 84 83 96 9c 96 2a d0 75 99 dd 38 7c 7c 5b 7d c8 a5 0c 6a 40 13 32> }
completed
  apn 0 left to send +2ms
  apn 0 left to send +1ms
  apn Notification 0 caused an error: 8 +109ms
transmissionError 8 { encoding: 'utf8',
  payload: 
   { description: 'This is a test',
     aps: { badge: 1, sound: 'dong.aiff', alert: 'Testing' } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  alert: 'Testing',
  badge: 1,
  sound: 'dong.aiff',
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: '{"description":"This is a test","aps":{"badge":1,"sound":"dong.aiff","alert":"Testing"}}',
  truncateAtWordEnd: false,
  urlArgs: undefined,
  category: undefined } { token: <Buffer c6 ce ac 1e f7 f5 ed c8 13 66 84 83 96 9c 96 2a d0 75 99 dd 38 7c 7c 5b 7d c8 a5 0c 6a 40 13 32> }
  apn Raising error: +1ms 8 { encoding: 'utf8',
  payload: 
   { description: 'This is a test',
     aps: { badge: 1, sound: 'dong.aiff', alert: 'Testing' } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  alert: 'Testing',
  badge: 1,
  sound: 'dong.aiff',
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: '{"description":"This is a test","aps":{"badge":1,"sound":"dong.aiff","alert":"Testing"}}',
  truncateAtWordEnd: false,
  urlArgs: undefined,
  category: undefined } { token: <Buffer c6 ce ac 1e f7 f5 ed c8 13 66 84 83 96 9c 96 2a d0 75 99 dd 38 7c 7c 5b 7d c8 a5 0c 6a 40 13 32> }
  apn Buffering 0 notifications for resending +0ms
  apn Socket closed +1ms 0
  apn Removing socket from pool +0ms 0
disconnected 0
  apn 0 left to send +0ms
```

Development Settings:
```
$ DEBUG=apn node push_notification.js
  apn Initialising connection +0ms
  apn Initialising module +2ms
  apn 1 left to send +3ms
  apn Connection established +325ms
connected 1
  apn Socket drained +106ms 0
transmitted { encoding: 'utf8',
  payload: 
   { description: 'This is a test',
     aps: { badge: 1, sound: 'dong.aiff', alert: 'Testing' } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  alert: 'Testing',
  badge: 1,
  sound: 'dong.aiff',
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: '{"description":"This is a test","aps":{"badge":1,"sound":"dong.aiff","alert":"Testing"}}',
  truncateAtWordEnd: false,
  urlArgs: undefined,
  category: undefined } { token: <Buffer c6 ce ac 1e f7 f5 ed c8 13 66 84 83 96 9c 96 2a d0 75 99 dd 38 7c 7c 5b 7d c8 a5 0c 6a 40 13 32> }
completed
  apn 0 left to send +3ms
  apn 0 left to send +0ms
^^^^^^^^[SCRIPT HANGS HERE]^^^^^^^^^
```

push_notification.js:
```
var apn = require("apn");
 
var connection = new apn.Connection({
    production:[true/false],
    key: "aps_[development/production].key.pem",
    cert: "aps_[development/production].cert.pem"
});

connection.addListener('error', console.error);
connection.addListener('socketError', console.error);

connection.addListener('transmitted', function(notification, device) {
    console.log('transmitted',notification, device);
});

connection.addListener('completed', function() {
    console.log('completed');
});

connection.addListener('cacheTooSmall', function(sizeDifference) {
    console.log('cacheTooSmall',sizeDifference);
});

connection.addListener('connected', function(openSockets) {
    console.log('connected',openSockets);
});

connection.addListener('disconnected', function(openSockets) {
    console.log('disconnected',openSockets);
});

connection.addListener('timeout', function(err) {
    console.log('timeout',err);
});

connection.addListener('transmissionError', function(errorCode, notification, device) {
    console.log('transmissionError',errorCode, notification, device);
});

var notification = new apn.Notification();
notification.payload = {"description": "This is a test"};
notification.badge = 1;
notification.sound = "dong.aiff";
notification.alert = "Testing";

var device = new apn.Device("c6ceac1ef7f5edc813668483969c962ad07599dd387c7c5b7dc8a50c6a401332");

connection.pushNotification(notification,device);
```

**Comment by argon** [comment] 2015-04-07 22:05
Is the device token you're using with the production environment generated by an app downloaded from the App Store?

\A

**Comment by mattfiocca** [comment] 2015-04-07 22:12
no, your right, i shouldn't be trying the production yet, i'm still building the development version of the app directly to my device in xcode. I just wanted to try the different environments to see if something became obvious with the certs. 

Do you know why when using the development certs, production:false, that my script above just hangs after the complete event is triggered?

**Comment by argon** [comment] 2015-04-07 22:15
That is the intended behaviour. It will keep the socket open ready to send more notifications. If you want it to complete call connection.shutdown() after pushing your notification. This probably isn't the behaviour you want though.

\A

**Comment by mattfiocca** [comment] 2015-04-07 22:21
Ok thanks. sounds like things are working right on the node side... now i just have to figure out why i'm not receiving the notifs on my device in dev. I have notifications allowed on this device for this app ... fresh set of certs etc. Thats all probably outside the scope of this project though, thanks Argon

**Comment by mattfiocca** [comment] 2015-04-07 22:41
ok, so, i just deleted all the provisioning profiles from the device, and rebuilt the app. i'm getting notifications to come in. I just must have had a mucked up profile.

**Comment by jakeapeters** [comment] 2015-05-13 12:33
In case it helps anyone in the future, I've just had this error. The notifications were all working great on the dev builds, but when I pushed to production I was failing to push new tokens from the devices. So essentially I was using development device tokens in the production environment, so they were in fact invalid.

So if anyone else has this problem and knows their certificates are fine, clear out your device tokens and try again!

**Closed** 2015-05-25 12:50 UTC

**Comment by sagar1987** [comment] 2016-03-16 06:25
var apn = require('apn');


var message = new apn.notification();

message.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
message.badge = 1;
message.sound = "ping.aiff";
message.setAlertText("You have new requests to Approve");
message.payload = { 'messageFrom': 'Holly' };

var options = { "gateway": "gateway.sandbox.push.apple.com", "cert": __dirname + "/_cert/cert.pem", "key": __dirname + "/_cert/key.pem", "passphrase:": "1234" };
var service = new apn.connection(options);

service.on('connected', function () {
    console.log("Connected");
});

service.on('transmitted', function (notification, device) {
    console.log("Notification transmitted to:" + device.token);
});

service.on('transmissionError', function (errCode, notification, device) {
    console.error("Notification caused error: " + errCode + " for device ", device, notification);
});

service.on('timeout', function () {
    console.log("Connection Timeout");
});

service.on('disconnected', function () {
    console.log("Disconnected from APNS");
});

service.on('socketError', console.error);


var deviceId = "6f8a481a 8d7dcb28 8e71ae14 2c010795 32667afb 99ea65bc d4b8c008 addad9fc";
var device = new apn.Device(deviceId);
service.pushNotification(message, device);

I am getting error as 

Debugger listening on port 5858
 Notification caused error: 513 for device  Device {
  token: <Buffer 6f 8a 48 1a 8d 7d cb 28 8e 71 ae 14 2c 01 07 95 32 66 7a fb 99
ea 65 bc d4 b8 c0 08 ad da d9 fc> } { encoding: 'utf8',
  payload:
   { messageFrom: 'Holly',
     aps:
      { badge: 1,
        sound: 'ping.aiff',
        alert: 'You have new requests to Approve',
        'url-args': undefined,
        category: undefined } },
  expiry: 1458113040,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"messageFrom":"Holly","aps":{"badge":1,"sound":"ping.aiff","alert"
:"You have new requests to Approve"}}',
  truncateAtWordEnd: false,
  _badge: 1,
  _sound: 'ping.aiff',
  _alert: 'You have new requests to Approve' }
C:\Users\sagar.j\Documents\Visual Studio 2012\Projects\NodejsWebApp2\NodejsWebAp
p2\node_modules\q\q.js:155
                throw e;
                ^

Error: error:0906A068:PEM routines:PEM_do_header:bad password read
    at Error (native)
    at Object.createSecureContext (_tls_common.js:87:19)
    at Object.TLSSocket._init.ssl.onclienthello.ssl.oncertcb.exports.connect (_t
ls_wrap.js:1003:48)
    at apnSocket (C:\Users\sagar.j\Documents\Visual Studio 2012\Projects\NodejsW
ebApp2\NodejsWebApp2\node_modules\apn\lib\socket.js:56:19)
    at Connection.<anonymous> (C:\Users\sagar.j\Documents\Visual Studio 2012\Pro
jects\NodejsWebApp2\NodejsWebApp2\node_modules\apn\lib\connection.js:199:17)
    at _fulfilled (C:\Users\sagar.j\Documents\Visual Studio 2012\Projects\Nodejs
WebApp2\NodejsWebApp2\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\sagar.j\Documents\Visual Studio 2012\
Projects\NodejsWebApp2\NodejsWebApp2\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\sagar.j\Documents\Visual Studio
 2012\Projects\NodejsWebApp2\NodejsWebApp2\node_modules\q\q.js:796:13)
    at C:\Users\sagar.j\Documents\Visual Studio 2012\Projects\NodejsWebApp2\Node
jsWebApp2\node_modules\q\q.js:604:44
    at runSingle (C:\Users\sagar.j\Documents\Visual Studio 2012\Projects\NodejsW
ebApp2\NodejsWebApp2\node_modules\q\q.js:137:13)
 Press any key to continue...
